steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_BACKEND_SERVICE}/backend:$SHORT_SHA'
      - '-t'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_BACKEND_SERVICE}/backend:latest'
      - './backend'
    id: 'build-backend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_BACKEND_SERVICE}/backend'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE}'
      - '--image'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_BACKEND_SERVICE}/backend:$SHORT_SHA'
      - '--region'
      - '${_GAR_LOCATION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},PORT=8080,NODE_ENV=production,FRONTEND_URL=${_FRONTEND_URL}'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Get backend URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe ${_BACKEND_SERVICE} --region=${_GAR_LOCATION} --format='value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        echo "$BACKEND_URL" > /workspace/backend-url.txt
    id: 'get-backend-url'
    waitFor: ['deploy-backend']

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=$$(cat /workspace/backend-url.txt)'
      - '-t'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_FRONTEND_SERVICE}/frontend:$SHORT_SHA'
      - '-t'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_FRONTEND_SERVICE}/frontend:latest'
      - './frontend'
    id: 'build-frontend'
    waitFor: ['get-backend-url']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_FRONTEND_SERVICE}/frontend'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_FRONTEND_SERVICE}'
      - '--image'
      - '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_FRONTEND_SERVICE}/frontend:$SHORT_SHA'
      - '--region'
      - '${_GAR_LOCATION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_BASE_URL=$$(cat /workspace/backend-url.txt)'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _GAR_LOCATION: 'us-central1'
  _BACKEND_SERVICE: 'exit-intent-popup-backend'
  _FRONTEND_SERVICE: 'exit-intent-popup-frontend'
  _DATABASE_URL: 'postgresql://user:password@host:5432/dbname'
  _FRONTEND_URL: 'https://your-frontend-url.run.app'


